#!/usr/bin/env python
# This software is under the terms of the GNU General Public License v3

# Name: network
# Usage: [python\s|\./]network [bashserver|puppetserver|lamp|nagios|erpnext]
# Description: Gets address of virtual machine

# IMPORTS
import sys

# LOCAL VARIABLES
machine = sys.argv[1]

# IP MACHINES
def debian():
    print "192.168.1.10"
def server():
    print "192.168.1.11"
def ubuntu():
    print "192.168.1.100"

# DICTIONARY TO GET IP
{'debian': debian,
 'server': server
}[machine]()
