#!/bin/bash
# This software is under the terms of the GNU General Public License v3

# Name: startvm 
# Usage: [bash\s|\./]startvm [debian|bashserver|puppetserver|lamp|nagios|erpnext]
# Description: Starts a virtual machine

# CLOSE VIRTUAL MACHINE
MACHINE=$1
VBoxManage startvm $MACHINE --type headless
