#!/bin/bash
# This software is under the terms of the GNU General Public License v3

# Name: unregistervm
# Usage: [bash\s|\./]unregistervm [debian|bashserver|puppetserver|lamp|nagios|erpnext]
# Description: Unregisters a virtual machine

# LOCAL VARIABLES
MACHINE=$1

# UNREGISTER $MACHINE
VBoxManage unregistervm $MACHINE
